baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Sleepless Camel'

author = "Sleepless Camel"
description = "Ramblings"

paginate = 5
summaryLength = 30

[params]
    favicon = "static/favicon.png"
    faviconIco = "static/favicon.png"
    
    showRss = false
    fontFamily = "Iosevka Nerd Font"
    titleFontFamily = "Iosevka Nerd Font"
    monospaceFontFamily = "Iosevka Nerd Font"