baseURL = 'https://sleeplessCamel.github.io/'
languageCode = 'en-us'
title = 'sleeplessCamel'
enableEmoji = true
enableRobotsTXT = true

# required
[build]
  _merge = 'deep'

# required
[markup]
  _merge = 'deep'

# for better SEO
[minify]
  _merge = 'deep'

# required module settings
[module]
[[module.mounts]]
  source = 'assets'
  target = 'assets'
[[module.mounts]]
  source = "hugo_stats.json"
  target = "assets/watching/hugo_stats.json"
[[module.imports]]
  path="github.com/canstand/compost"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[pagination]
  pagerSize = 5

[params]
  colorScheme = "auto"
  logo = "favicon.png"
  favicon = "favicon.png"

[params.homepage]
  showRecent = false

[params.article]
  showBreadcrumbs = true
  showEdit = true
  editURL = "https://github.com/sleeplessCamel/sleeplessCamel.github.io/"
  editAppendPath = true

[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "Blog"
  pageRef = "posts"
  weight = 10

[[menu.main]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/sleeplessCamel"
  weight = 30